Script.Load("E:/Repositories/symfonia/qsb/lua/core.lua")
Script.Load("E:/Repositories/symfonia/qsb/lua/bundles/bundleclassicbehaviors/source.lua")
Script.Load("E:/Repositories/symfonia/qsb/lua/bundles/bundlesymfoniabehaviors/source.lua")
Script.Load("E:/Repositories/symfonia/qsb/lua/bundles/bundlequestdebug/source.lua")
Script.Load("E:/Repositories/symfonia/qsb/lua/bundles/bundlequestgeneration/source.lua")